// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD36RlnZdD1MBDqxDS7QUoqP-k5XCMuUMM',
    appId: '1:76289614313:web:34622a97d52814604eeb78',
    messagingSenderId: '76289614313',
    projectId: 'roshan-alert',
    authDomain: 'roshan-alert.firebaseapp.com',
    storageBucket: 'roshan-alert.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYjiUbn6qh59sZIzSTv-WGdktZxeCJBVc',
    appId: '1:76289614313:android:c835b56e619b91574eeb78',
    messagingSenderId: '76289614313',
    projectId: 'roshan-alert',
    storageBucket: 'roshan-alert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNSkc56UOzvDB8eJsAHrWh8X-jWE_18Cg',
    appId: '1:76289614313:ios:b67c6d49a638d9914eeb78',
    messagingSenderId: '76289614313',
    projectId: 'roshan-alert',
    storageBucket: 'roshan-alert.firebasestorage.app',
    iosBundleId: 'com.example.roshanAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNSkc56UOzvDB8eJsAHrWh8X-jWE_18Cg',
    appId: '1:76289614313:ios:b67c6d49a638d9914eeb78',
    messagingSenderId: '76289614313',
    projectId: 'roshan-alert',
    storageBucket: 'roshan-alert.firebasestorage.app',
    iosBundleId: 'com.example.roshanAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD36RlnZdD1MBDqxDS7QUoqP-k5XCMuUMM',
    appId: '1:76289614313:web:671b9d24b0cabb174eeb78',
    messagingSenderId: '76289614313',
    projectId: 'roshan-alert',
    authDomain: 'roshan-alert.firebaseapp.com',
    storageBucket: 'roshan-alert.firebasestorage.app',
  );
}
